generates numbers and displays them
Kimmiich/Tidsestimatspoker-Frontend pull request #22
Opened 2021-10-13 10:37 UTC by ssmeds

Skapat en ny komponent som ska ta in data från databasen och räkna ut dem till de olika värdena som ska visas. Samt lagt till inputfält och knappar för att spara nya värden.

2021-10-13 10:56 UTC, EmilNilsson12 requested changes

2021-10-13 10:56 UTC, EmilNilsson12 commented on src/Components/Summary.tsx
> +}
Dessa kanske kan flyttas till en egen fil i helperFunctions mappen?

2021-10-13 10:56 UTC, EmilNilsson12 commented on src/Components/Summary.tsx
> +const Summary = () => {
Summary borde ta minVal, maxVal, medianVal, averageVal som props

2021-10-13 10:56 UTC, EmilNilsson12 commented on src/components/Issue.tsx
> +        <button style={{padding:'0.6rem'}}>Spara</button>
Denna finns redan som egen komponent i Components/TimeEstimationForm/TimeEstimationForm.jsx

2021-10-13 11:12 UTC, ssmeds commented on src/components/Issue.tsx
> +        <button style={{padding:'0.6rem'}}>Spara</button>
Ja, jag såg det också. Jag kan ta bort den från min.

2021-10-13 11:12 UTC, ssmeds commented on src/Components/Summary.tsx
> +}
Yes, har fixat nu!

2021-10-14 06:59 UTC, Kimmiich approved these changes

2021-10-14 07:06 UTC, loveefraimsson approved these changes

2021-10-14 08:59 UTC, ssmeds commented on src/Components/Summary.tsx
> +const Summary = () => {
Har gjort detta, med interface men fått lite problem med propsen när jag infogar komponenten.

2021-10-14 13:33 UTC, EmilNilsson12 requested changes

2021-10-14 13:33 UTC, EmilNilsson12 commented on src/Components/Summary.tsx
> +}
Jag tänkte att props borde vara en array av samma typ som // Testsiffror på rad 8.
Alltså en array med 5 siffror, en siffra för varje gruppmedlem.

Sen räknas minVal m.m. fram utifrån den arrayen.

2021-10-16 20:02 UTC, EmilNilsson12 approved these changes

2021-10-18 11:57 UTC, merged